apiVersion: v1
kind: Service
metadata:
  namespace: kubeflow
  labels:
    app: mlflow-tracking-server
  name: mlflow-tracking-server
spec:
  type: ExternalName
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: mlflow-tracking-server-pods
  externalName: mlflow.svc.cluster
