apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mlflow-svc
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /mlflow/
    route:
    - destination:
        port:
          number: 5000
        host: mlflow.svc.cluster